from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
css = (ROOT / "frontend/app/globals.css").read_text(encoding="utf-8").replace('@import "tailwindcss";','',1)
out = ROOT / "scripts/fixtures/ui_r87_rev1_ownership_harness.html"
html = f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>{css}
.preview-shell-r87{{display:grid;grid-template-columns:220px minmax(0,1fr);min-height:100vh;background:var(--creed-background)}}
.preview-sidebar-r87{{border-right:1px solid var(--creed-border-subtle);background:var(--creed-surface);padding:22px 12px}}
.preview-brand-r87{{padding:0 10px 20px;color:var(--creed-off-white);font-weight:800;letter-spacing:.08em}}
.preview-nav-r87{{display:grid;gap:4px}}.preview-nav-r87 span{{padding:9px 10px;border-radius:4px;color:var(--creed-muted);font-size:12px}}.preview-nav-r87 span.active{{background:var(--creed-surface-hover);color:var(--creed-off-white)}}
.preview-main-r87{{min-width:0;padding:30px 36px 48px}}.preview-top-r87{{margin-bottom:26px;color:var(--creed-muted);font-size:11px}}
@media(max-width:760px){{.preview-shell-r87{{display:block}}.preview-sidebar-r87{{display:none}}.preview-main-r87{{padding:22px 16px 38px}}}}
</style></head><body><div class="preview-shell-r87"><aside class="preview-sidebar-r87"><div class="preview-brand-r87">CREED</div><div class="preview-nav-r87"><span>Overview</span><span>Issues</span><span>Change Radar</span><span>Clients</span><span>Implementations</span><span>Deployments</span><span>Methods</span><span>Dependencies</span><span>Authority</span><span class="active">Ownership</span><span>Knowledge</span><span>Recalls</span><span>Audit</span></div></aside><main class="preview-main-r87"><div class="preview-top-r87">CREED / Ownership &amp; responsibility</div><div class="page ownership-registry-r87">
<div class="title-row ownership-registry-title-r87"><div><h1>Ownership &amp; responsibility</h1><p class="subtitle">Map accountable people to products, modules, implementations and reusable methods. Ownership clarifies who is responsible; governance authority remains controlled separately.</p><div class="ownership-summary-r87"><span><strong>8</strong> assignments</span><span><strong>6</strong> assets covered</span><span><strong>4</strong> accountable principals</span><span class="attention"><strong>1</strong> attention</span></div></div><button class="primary-btn">Assign responsibility</button></div>
<section class="ownership-create-r87"><div class="ownership-create-head-r87"><div><h2>Assign responsibility</h2><p>Assign one current accountable principal per asset and responsibility role. Existing ownership cannot be silently replaced.</p></div></div><div class="ownership-create-form-r87"><label class="ownership-field-r87"><span>Scope <b>Required</b></span><select><option>Module</option></select><small>What kind of delivery asset owns the responsibility.</small></label><label class="ownership-field-r87 ownership-target-field-r87"><span>Asset <b>Required</b></span><select><option>Promise-to-Pay — Collections / Promise-to-Pay</option></select><small>Select the persisted CREED asset.</small></label><label class="ownership-field-r87"><span>Responsibility <b>Required</b></span><select><option>Module owner</option></select><small>Roles are constrained by the selected scope.</small></label><label class="ownership-field-r87"><span>Accountable principal <b>Required</b></span><select><option>Aisha Rahman — Transformation Assurance Lead</option></select><small>Uses the stable principal from Human Authority.</small></label><label class="ownership-field-r87"><span>Team <b>Optional</b></span><input value="Collections Delivery" readonly><small>Team context only; accountability remains attached to the named principal.</small></label><div class="ownership-create-context-r87"><span>◆</span><span>Responsibility is not permission. This assignment does not grant Human Decision, learning approval or recall authorization rights.</span></div><div class="ownership-create-actions-r87"><button class="secondary-btn">Cancel</button><button class="primary-btn">Assign responsibility</button></div></div></section>
<section class="ownership-ledger-r87"><div class="ownership-ledger-head-r87"><div><h2>Responsibility ledger</h2><span>3 shown of 8</span></div><div class="ownership-ledger-controls-r87"><label class="ownership-search-r87"><span>⌕</span><input placeholder="Search asset, owner or team"></label><label class="ownership-filter-r87"><select><option>All scopes</option></select></label><label class="ownership-filter-r87"><select><option>All responsibilities</option></select></label></div></div><div class="ownership-table-r87"><div class="ownership-table-columns-r87"><span>Asset</span><span>Responsibility</span><span>Accountable principal</span><span>State</span><span>Action</span></div>
<article class="ownership-record-r87"><div class="ownership-row-r87"><div class="ownership-asset-r87" data-label="Asset"><span class="ownership-scope-icon-r87">▦</span><span><strong>Promise-to-Pay</strong><small>Collections / Promise-to-Pay</small><code>MODULE · mod-ptp-104</code></span></div><div class="ownership-role-r87" data-label="Responsibility"><strong>Module owner</strong><code>MODULE_OWNER</code></div><div class="ownership-principal-r87" data-label="Accountable principal"><span>◎</span><span><strong>Aisha Rahman</strong><small>Transformation Assurance Lead · Collections Delivery</small><code>aisha.rahman@company.com</code></span></div><div class="ownership-state-r87" data-label="State"><span class="ownership-state-label-r87 ok">✓ Active principal</span><small>Updated 20/08/2026</small></div><div class="ownership-action-r87" data-label="Action"><button class="secondary-btn compact">Maintain</button></div></div></article>
<article class="ownership-record-r87"><div class="ownership-row-r87"><div class="ownership-asset-r87" data-label="Asset"><span class="ownership-scope-icon-r87">↗</span><span><strong>Atlas PTP Implementation</strong><small>Atlas Bank · Collections / Promise-to-Pay · R4.2</small><code>IMPLEMENTATION · impl-atlas-42</code></span></div><div class="ownership-role-r87" data-label="Responsibility"><strong>Implementation lead</strong><code>IMPLEMENTATION_LEAD</code></div><div class="ownership-principal-r87" data-label="Accountable principal"><span>◎</span><span><strong>Daniel Lim</strong><small>Implementation Lead · Core Banking Delivery</small><code>daniel.lim@company.com</code></span></div><div class="ownership-state-r87" data-label="State"><span class="ownership-state-label-r87 ok">✓ Active principal</span><small>Updated 19/08/2026</small></div><div class="ownership-action-r87" data-label="Action"><button class="secondary-btn compact">Maintain</button></div></div></article>
<article class="ownership-record-r87 needs-attention"><div class="ownership-row-r87"><div class="ownership-asset-r87" data-label="Asset"><span class="ownership-scope-icon-r87">⑂</span><span><strong>PTP Event Handling</strong><small>Collections / Promise-to-Pay</small><code>METHOD · method-ptp-event</code></span></div><div class="ownership-role-r87" data-label="Responsibility"><strong>Technical owner</strong><code>TECHNICAL_OWNER</code></div><div class="ownership-principal-r87" data-label="Accountable principal"><span>◎</span><span><strong>Marcus Tan</strong><small>Principal Engineer</small><code>marcus.tan@company.com</code></span></div><div class="ownership-state-r87" data-label="State"><span class="ownership-state-label-r87 warn">! Principal inactive</span><small>Updated 14/08/2026</small></div><div class="ownership-action-r87" data-label="Action"><button class="secondary-btn compact">Maintain</button></div></div></article>
</div></section></div></main></div></body></html>'''
out.write_text(html, encoding="utf-8")
print(out)
