"""M20 integrated intelligence governance demo

Revision ID: cfd6e75baf98
Revises: c8d9e0f1a2b3
Create Date: 2026-08-15 13:17:18.492799
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cfd6e75baf98'
down_revision: Union[str, None] = 'c8d9e0f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_evidence_hits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('matched_queries_json', sa.JSON(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.Column('query_coverage_bonus', sa.Float(), nullable=False),
    sa.Column('issue_link_boost', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('keyword_score', sa.Float(), nullable=False),
    sa.Column('metadata_score', sa.Float(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=180), nullable=True),
    sa.Column('embedding_degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['support_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'chunk_id', name='uq_analysis_evidence_run_chunk')
    )
    op.create_index(op.f('ix_analysis_evidence_hits_agent_run_id'), 'analysis_evidence_hits', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_analysis_evidence_hits_chunk_id'), 'analysis_evidence_hits', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_analysis_evidence_hits_document_id'), 'analysis_evidence_hits', ['document_id'], unique=False)
    op.create_index(op.f('ix_analysis_evidence_hits_final_score'), 'analysis_evidence_hits', ['final_score'], unique=False)
    op.create_index(op.f('ix_analysis_evidence_hits_issue_id'), 'analysis_evidence_hits', ['issue_id'], unique=False)
    op.create_index('ix_analysis_evidence_run_rank', 'analysis_evidence_hits', ['agent_run_id', 'rank'], unique=False)
    op.create_table('analysis_impact_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('implementation_id', sa.String(length=36), nullable=False),
    sa.Column('method_version_id', sa.String(length=36), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('impact_band', sa.String(length=40), nullable=False),
    sa.Column('reported_source', sa.Boolean(), nullable=False),
    sa.Column('signals_json', sa.JSON(), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('explanation_json', sa.JSON(), nullable=False),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['support_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_version_id'], ['method_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'implementation_id', name='uq_impact_run_implementation')
    )
    op.create_index(op.f('ix_analysis_impact_assessments_agent_run_id'), 'analysis_impact_assessments', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_analysis_impact_assessments_impact_band'), 'analysis_impact_assessments', ['impact_band'], unique=False)
    op.create_index(op.f('ix_analysis_impact_assessments_implementation_id'), 'analysis_impact_assessments', ['implementation_id'], unique=False)
    op.create_index(op.f('ix_analysis_impact_assessments_issue_id'), 'analysis_impact_assessments', ['issue_id'], unique=False)
    op.create_index(op.f('ix_analysis_impact_assessments_method_version_id'), 'analysis_impact_assessments', ['method_version_id'], unique=False)
    op.create_index('ix_impact_run_score', 'analysis_impact_assessments', ['agent_run_id', 'impact_score'], unique=False)
    op.create_table('method_version_lineage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_method_version_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_method_version_id', sa.String(length=36), nullable=False),
    sa.Column('correction_input', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=180), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposed_method_version_id'], ['method_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_method_version_id'], ['method_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_method_version_lineage_proposed_method_version_id'), 'method_version_lineage', ['proposed_method_version_id'], unique=True)
    op.create_index(op.f('ix_method_version_lineage_source_method_version_id'), 'method_version_lineage', ['source_method_version_id'], unique=False)
    op.create_table('investigation_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('qwen_run_id', sa.String(length=140), nullable=True),
    sa.Column('configured_model', sa.String(length=180), nullable=True),
    sa.Column('actual_model', sa.String(length=180), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('prompt_eval_count', sa.Integer(), nullable=True),
    sa.Column('eval_count', sa.Integer(), nullable=True),
    sa.Column('evidence_observations_json', sa.JSON(), nullable=False),
    sa.Column('missing_evidence_json', sa.JSON(), nullable=False),
    sa.Column('model_output_json', sa.JSON(), nullable=False),
    sa.Column('evidence_validation_status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_details_agent_run_id'), 'investigation_details', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_investigation_details_evidence_validation_status'), 'investigation_details', ['evidence_validation_status'], unique=False)
    op.create_index(op.f('ix_investigation_details_finding_id'), 'investigation_details', ['finding_id'], unique=False)
    op.create_index(op.f('ix_investigation_details_investigation_id'), 'investigation_details', ['investigation_id'], unique=True)
    op.create_index(op.f('ix_investigation_details_qwen_run_id'), 'investigation_details', ['qwen_run_id'], unique=False)
    op.create_table('learning_proposal_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learning_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('source_method_version_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('correction_input', sa.Text(), nullable=False),
    sa.Column('applicability', sa.Text(), nullable=False),
    sa.Column('guardrails_json', sa.JSON(), nullable=False),
    sa.Column('validation_steps_json', sa.JSON(), nullable=False),
    sa.Column('qwen_run_id', sa.String(length=140), nullable=True),
    sa.Column('configured_model', sa.String(length=180), nullable=True),
    sa.Column('actual_model', sa.String(length=180), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('prompt_eval_count', sa.Integer(), nullable=True),
    sa.Column('eval_count', sa.Integer(), nullable=True),
    sa.Column('model_output_json', sa.JSON(), nullable=False),
    sa.Column('human_edited_by', sa.String(length=180), nullable=True),
    sa.Column('human_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_by', sa.String(length=180), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learning_id'], ['learning_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_method_version_id'], ['method_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_proposal_details_agent_run_id'), 'learning_proposal_details', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_learning_proposal_details_learning_id'), 'learning_proposal_details', ['learning_id'], unique=True)
    op.create_index(op.f('ix_learning_proposal_details_qwen_run_id'), 'learning_proposal_details', ['qwen_run_id'], unique=False)
    op.create_index(op.f('ix_learning_proposal_details_source_method_version_id'), 'learning_proposal_details', ['source_method_version_id'], unique=False)
    op.create_table('recall_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recall_notice_id', sa.String(length=36), nullable=False),
    sa.Column('implementation_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_edge_id', sa.String(length=36), nullable=True),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependency_edge_id'], ['dependency_edges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recall_notice_id'], ['recall_notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recall_notice_id', 'implementation_id', name='uq_recall_implementation')
    )
    op.create_index(op.f('ix_recall_cases_dependency_edge_id'), 'recall_cases', ['dependency_edge_id'], unique=False)
    op.create_index(op.f('ix_recall_cases_implementation_id'), 'recall_cases', ['implementation_id'], unique=False)
    op.create_index(op.f('ix_recall_cases_investigation_id'), 'recall_cases', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_recall_cases_recall_notice_id'), 'recall_cases', ['recall_notice_id'], unique=False)
    op.create_index(op.f('ix_recall_cases_status'), 'recall_cases', ['status'], unique=False)
    op.create_table('recall_notice_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recall_notice_id', sa.String(length=36), nullable=False),
    sa.Column('source_issue_id', sa.String(length=36), nullable=False),
    sa.Column('recall_run_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('affected_implementation_ids_json', sa.JSON(), nullable=False),
    sa.Column('notice_payload_json', sa.JSON(), nullable=False),
    sa.Column('attestation_statement', sa.Text(), nullable=False),
    sa.Column('notice_version', sa.String(length=40), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['recall_notice_id'], ['recall_notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recall_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_issue_id'], ['support_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recall_notice_details_recall_notice_id'), 'recall_notice_details', ['recall_notice_id'], unique=True)
    op.create_index(op.f('ix_recall_notice_details_recall_run_id'), 'recall_notice_details', ['recall_run_id'], unique=False)
    op.create_index(op.f('ix_recall_notice_details_source_issue_id'), 'recall_notice_details', ['source_issue_id'], unique=False)
    op.create_table('adoption_receipt_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('source_issue_id', sa.String(length=36), nullable=False),
    sa.Column('source_method_version_id', sa.String(length=36), nullable=False),
    sa.Column('adopted_method_version_id', sa.String(length=36), nullable=False),
    sa.Column('approval_reason', sa.Text(), nullable=False),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('receipt_payload_json', sa.JSON(), nullable=False),
    sa.Column('attestation_statement', sa.Text(), nullable=False),
    sa.Column('receipt_version', sa.String(length=40), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['adopted_method_version_id'], ['method_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['adoption_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_issue_id'], ['support_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_method_version_id'], ['method_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_receipt_details_adopted_method_version_id'), 'adoption_receipt_details', ['adopted_method_version_id'], unique=False)
    op.create_index(op.f('ix_adoption_receipt_details_receipt_id'), 'adoption_receipt_details', ['receipt_id'], unique=True)
    op.create_index(op.f('ix_adoption_receipt_details_source_issue_id'), 'adoption_receipt_details', ['source_issue_id'], unique=False)
    op.create_index(op.f('ix_adoption_receipt_details_source_method_version_id'), 'adoption_receipt_details', ['source_method_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoption_receipt_details_source_method_version_id'), table_name='adoption_receipt_details')
    op.drop_index(op.f('ix_adoption_receipt_details_source_issue_id'), table_name='adoption_receipt_details')
    op.drop_index(op.f('ix_adoption_receipt_details_receipt_id'), table_name='adoption_receipt_details')
    op.drop_index(op.f('ix_adoption_receipt_details_adopted_method_version_id'), table_name='adoption_receipt_details')
    op.drop_table('adoption_receipt_details')
    op.drop_index(op.f('ix_recall_notice_details_source_issue_id'), table_name='recall_notice_details')
    op.drop_index(op.f('ix_recall_notice_details_recall_run_id'), table_name='recall_notice_details')
    op.drop_index(op.f('ix_recall_notice_details_recall_notice_id'), table_name='recall_notice_details')
    op.drop_table('recall_notice_details')
    op.drop_index(op.f('ix_recall_cases_status'), table_name='recall_cases')
    op.drop_index(op.f('ix_recall_cases_recall_notice_id'), table_name='recall_cases')
    op.drop_index(op.f('ix_recall_cases_investigation_id'), table_name='recall_cases')
    op.drop_index(op.f('ix_recall_cases_implementation_id'), table_name='recall_cases')
    op.drop_index(op.f('ix_recall_cases_dependency_edge_id'), table_name='recall_cases')
    op.drop_table('recall_cases')
    op.drop_index(op.f('ix_learning_proposal_details_source_method_version_id'), table_name='learning_proposal_details')
    op.drop_index(op.f('ix_learning_proposal_details_qwen_run_id'), table_name='learning_proposal_details')
    op.drop_index(op.f('ix_learning_proposal_details_learning_id'), table_name='learning_proposal_details')
    op.drop_index(op.f('ix_learning_proposal_details_agent_run_id'), table_name='learning_proposal_details')
    op.drop_table('learning_proposal_details')
    op.drop_index(op.f('ix_investigation_details_qwen_run_id'), table_name='investigation_details')
    op.drop_index(op.f('ix_investigation_details_investigation_id'), table_name='investigation_details')
    op.drop_index(op.f('ix_investigation_details_finding_id'), table_name='investigation_details')
    op.drop_index(op.f('ix_investigation_details_evidence_validation_status'), table_name='investigation_details')
    op.drop_index(op.f('ix_investigation_details_agent_run_id'), table_name='investigation_details')
    op.drop_table('investigation_details')
    op.drop_index(op.f('ix_method_version_lineage_source_method_version_id'), table_name='method_version_lineage')
    op.drop_index(op.f('ix_method_version_lineage_proposed_method_version_id'), table_name='method_version_lineage')
    op.drop_table('method_version_lineage')
    op.drop_index('ix_impact_run_score', table_name='analysis_impact_assessments')
    op.drop_index(op.f('ix_analysis_impact_assessments_method_version_id'), table_name='analysis_impact_assessments')
    op.drop_index(op.f('ix_analysis_impact_assessments_issue_id'), table_name='analysis_impact_assessments')
    op.drop_index(op.f('ix_analysis_impact_assessments_implementation_id'), table_name='analysis_impact_assessments')
    op.drop_index(op.f('ix_analysis_impact_assessments_impact_band'), table_name='analysis_impact_assessments')
    op.drop_index(op.f('ix_analysis_impact_assessments_agent_run_id'), table_name='analysis_impact_assessments')
    op.drop_table('analysis_impact_assessments')
    op.drop_index('ix_analysis_evidence_run_rank', table_name='analysis_evidence_hits')
    op.drop_index(op.f('ix_analysis_evidence_hits_issue_id'), table_name='analysis_evidence_hits')
    op.drop_index(op.f('ix_analysis_evidence_hits_final_score'), table_name='analysis_evidence_hits')
    op.drop_index(op.f('ix_analysis_evidence_hits_document_id'), table_name='analysis_evidence_hits')
    op.drop_index(op.f('ix_analysis_evidence_hits_chunk_id'), table_name='analysis_evidence_hits')
    op.drop_index(op.f('ix_analysis_evidence_hits_agent_run_id'), table_name='analysis_evidence_hits')
    op.drop_table('analysis_evidence_hits')
    # ### end Alembic commands ###
