"""initial CREED domain model

Revision ID: fd5e3c74bccf
Revises: 
Create Date: 2026-08-15 08:40:33.897902
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fd5e3c74bccf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=180), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index('ix_audit_object', 'audit_events', ['object_type', 'object_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('client_type', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('evidence_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_documents_content_hash'), 'evidence_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_documents_document_type'), 'evidence_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_evidence_documents_source'), 'evidence_documents', ['source'], unique=False)
    op.create_index(op.f('ix_evidence_documents_title'), 'evidence_documents', ['title'], unique=False)
    op.create_index('ix_evidence_source_hash', 'evidence_documents', ['source', 'content_hash'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('dependency_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['evidence_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', 'relationship', name='uq_dependency_edge')
    )
    op.create_index(op.f('ix_dependency_edges_evidence_document_id'), 'dependency_edges', ['evidence_document_id'], unique=False)
    op.create_index(op.f('ix_dependency_edges_relationship'), 'dependency_edges', ['relationship'], unique=False)
    op.create_index('ix_dependency_source', 'dependency_edges', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_dependency_target', 'dependency_edges', ['target_type', 'target_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_module_product_name')
    )
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=False)
    op.create_index(op.f('ix_modules_product_id'), 'modules', ['product_id'], unique=False)
    op.create_table('support_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_ticket_id', sa.String(length=120), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('issue_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_issues_client_id'), 'support_issues', ['client_id'], unique=False)
    op.create_index(op.f('ix_support_issues_external_ticket_id'), 'support_issues', ['external_ticket_id'], unique=False)
    op.create_index(op.f('ix_support_issues_issue_type'), 'support_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_support_issues_severity'), 'support_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_support_issues_status'), 'support_issues', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('graph_run_id', sa.String(length=140), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['support_issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_graph_run_id'), 'agent_runs', ['graph_run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_issue_id'), 'agent_runs', ['issue_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('delivery_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'name', name='uq_method_module_name')
    )
    op.create_index(op.f('ix_delivery_methods_module_id'), 'delivery_methods', ['module_id'], unique=False)
    op.create_index(op.f('ix_delivery_methods_name'), 'delivery_methods', ['name'], unique=False)
    op.create_table('implementations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('release_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'module_id', 'release_version', name='uq_implementation_release')
    )
    op.create_index(op.f('ix_implementations_client_id'), 'implementations', ['client_id'], unique=False)
    op.create_index(op.f('ix_implementations_module_id'), 'implementations', ['module_id'], unique=False)
    op.create_index(op.f('ix_implementations_product_id'), 'implementations', ['product_id'], unique=False)
    op.create_index(op.f('ix_implementations_status'), 'implementations', ['status'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_step_run_name', 'agent_steps', ['agent_run_id', 'agent_name'], unique=False)
    op.create_index(op.f('ix_agent_steps_agent_run_id'), 'agent_steps', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_status'), 'agent_steps', ['status'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('implementation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['support_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'implementation_id', name='uq_issue_implementation_investigation')
    )
    op.create_index(op.f('ix_investigations_implementation_id'), 'investigations', ['implementation_id'], unique=False)
    op.create_index(op.f('ix_investigations_issue_id'), 'investigations', ['issue_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_table('method_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('method_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['delivery_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method_id', 'version', name='uq_method_version')
    )
    op.create_index(op.f('ix_method_versions_method_id'), 'method_versions', ['method_id'], unique=False)
    op.create_index(op.f('ix_method_versions_status'), 'method_versions', ['status'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_finding_type'), 'findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_findings_investigation_id'), 'findings', ['investigation_id'], unique=False)
    op.create_table('human_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=80), nullable=False),
    sa.Column('reviewer', sa.String(length=180), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_decisions_decision'), 'human_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_human_decisions_investigation_id'), 'human_decisions', ['investigation_id'], unique=False)
    op.create_table('learning_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_issue_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_method_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposed_method_version_id'], ['method_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_issue_id'], ['support_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_proposals_proposed_method_version_id'), 'learning_proposals', ['proposed_method_version_id'], unique=False)
    op.create_index(op.f('ix_learning_proposals_source_issue_id'), 'learning_proposals', ['source_issue_id'], unique=False)
    op.create_index(op.f('ix_learning_proposals_status'), 'learning_proposals', ['status'], unique=False)
    op.create_table('recall_notices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revoked_version_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=180), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['revoked_version_id'], ['method_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_recall_notices_revoked_version_id'), 'recall_notices', ['revoked_version_id'], unique=False)
    op.create_index(op.f('ix_recall_notices_status'), 'recall_notices', ['status'], unique=False)
    op.create_table('adoption_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learning_id', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=180), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('adoption_scope', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['learning_id'], ['learning_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_adoption_receipts_learning_id'), 'adoption_receipts', ['learning_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoption_receipts_learning_id'), table_name='adoption_receipts')
    op.drop_table('adoption_receipts')
    op.drop_index(op.f('ix_recall_notices_status'), table_name='recall_notices')
    op.drop_index(op.f('ix_recall_notices_revoked_version_id'), table_name='recall_notices')
    op.drop_table('recall_notices')
    op.drop_index(op.f('ix_learning_proposals_status'), table_name='learning_proposals')
    op.drop_index(op.f('ix_learning_proposals_source_issue_id'), table_name='learning_proposals')
    op.drop_index(op.f('ix_learning_proposals_proposed_method_version_id'), table_name='learning_proposals')
    op.drop_table('learning_proposals')
    op.drop_index(op.f('ix_human_decisions_investigation_id'), table_name='human_decisions')
    op.drop_index(op.f('ix_human_decisions_decision'), table_name='human_decisions')
    op.drop_table('human_decisions')
    op.drop_index(op.f('ix_findings_investigation_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_type'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_method_versions_status'), table_name='method_versions')
    op.drop_index(op.f('ix_method_versions_method_id'), table_name='method_versions')
    op.drop_table('method_versions')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_issue_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_implementation_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_agent_steps_status'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_agent_run_id'), table_name='agent_steps')
    op.drop_index('ix_agent_step_run_name', table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_implementations_status'), table_name='implementations')
    op.drop_index(op.f('ix_implementations_product_id'), table_name='implementations')
    op.drop_index(op.f('ix_implementations_module_id'), table_name='implementations')
    op.drop_index(op.f('ix_implementations_client_id'), table_name='implementations')
    op.drop_table('implementations')
    op.drop_index(op.f('ix_delivery_methods_name'), table_name='delivery_methods')
    op.drop_index(op.f('ix_delivery_methods_module_id'), table_name='delivery_methods')
    op.drop_table('delivery_methods')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_issue_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_graph_run_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_support_issues_status'), table_name='support_issues')
    op.drop_index(op.f('ix_support_issues_severity'), table_name='support_issues')
    op.drop_index(op.f('ix_support_issues_issue_type'), table_name='support_issues')
    op.drop_index(op.f('ix_support_issues_external_ticket_id'), table_name='support_issues')
    op.drop_index(op.f('ix_support_issues_client_id'), table_name='support_issues')
    op.drop_table('support_issues')
    op.drop_index(op.f('ix_modules_product_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.drop_table('modules')
    op.drop_index('ix_dependency_target', table_name='dependency_edges')
    op.drop_index('ix_dependency_source', table_name='dependency_edges')
    op.drop_index(op.f('ix_dependency_edges_relationship'), table_name='dependency_edges')
    op.drop_index(op.f('ix_dependency_edges_evidence_document_id'), table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_evidence_source_hash', table_name='evidence_documents')
    op.drop_index(op.f('ix_evidence_documents_title'), table_name='evidence_documents')
    op.drop_index(op.f('ix_evidence_documents_source'), table_name='evidence_documents')
    op.drop_index(op.f('ix_evidence_documents_document_type'), table_name='evidence_documents')
    op.drop_index(op.f('ix_evidence_documents_content_hash'), table_name='evidence_documents')
    op.drop_table('evidence_documents')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_audit_object', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
